# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

# split panes using | and -
bind h split-window -h
bind v split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n h select-pane -L
bind -n j select-pane -D
bind -n k select-pane -U
bind -n l select-pane -R

# don't rename windows automatically
set-option -g allow-rename off
